function Hd = nd_designed_sexy
%ND_DESIGNED_SEXY Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 28-Dec-2020 11:09:34

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

Fstop1 = 730;         % First Stopband Frequency
Fpass1 = 3000;        % First Passband Frequency
Fpass2 = 5000;        % Second Passband Frequency
Fstop2 = 6800;        % Second Stopband Frequency
Astop1 = 50;          % First Stopband Attenuation (dB)
Apass  = 0.0005;      % Passband Ripple (dB)
Astop2 = 50;          % Second Stopband Attenuation (dB)
match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
